// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REDACTED_FIREBASE_ANDROID_API_KEY',
    appId: '1:1012962167727:android:dd7c267a1edf01c0e7bd5a',
    messagingSenderId: '1012962167727',
    projectId: 'mimzapp',
    storageBucket: 'mimzapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REDACTED_FIREBASE_IOS_API_KEY',
    appId: '1:1012962167727:ios:45c7af776d18210ce7bd5a',
    messagingSenderId: '1012962167727',
    projectId: 'mimzapp',
    storageBucket: 'mimzapp.firebasestorage.app',
    androidClientId: '1012962167727-0p0dn1t5snr5m1r8sb6hcun9t5b6j24n.apps.googleusercontent.com',
    iosClientId: '1012962167727-lorb8qhom0cvhe5nnj22ealeajf5uv5a.apps.googleusercontent.com',
    iosBundleId: 'com.mimz.mimzApp',
  );

}