// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const String _androidApiKey =
      String.fromEnvironment('FIREBASE_ANDROID_API_KEY');
  static const String _iosApiKey =
      String.fromEnvironment('FIREBASE_IOS_API_KEY');

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get android {
    if (_androidApiKey.isEmpty) {
      throw UnsupportedError(
        'Missing FIREBASE_ANDROID_API_KEY. Pass it via --dart-define.',
      );
    }
    return FirebaseOptions(
      apiKey: _androidApiKey,
      appId: '1:392547013333:android:7ae37e7927360219da485c',
      messagingSenderId: '392547013333',
      projectId: 'mimz-490520',
      storageBucket: 'mimz-490520.firebasestorage.app',
    );
  }

  static FirebaseOptions get ios {
    if (_iosApiKey.isEmpty) {
      throw UnsupportedError(
        'Missing FIREBASE_IOS_API_KEY. Pass it via --dart-define.',
      );
    }
    return FirebaseOptions(
      apiKey: _iosApiKey,
      appId: '1:392547013333:ios:c78be5bbda376bbfda485c',
      messagingSenderId: '392547013333',
      projectId: 'mimz-490520',
      storageBucket: 'mimz-490520.firebasestorage.app',
      androidClientId:
          '392547013333-51rid4rl2li0v5qf0kv6hhclb4umvgch.apps.googleusercontent.com',
      iosClientId:
          '392547013333-h66prhdk3ep7pa9pd6bue57advji0rel.apps.googleusercontent.com',
      iosBundleId: 'com.mimz.mimzApp',
    );
  }
}
